"""esquema inicial

Revision ID: 22614788248f
Revises: 
Fecha: 2026-08-18 23:56:55.462175-03:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '22614788248f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Aplica el cambio."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('product', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('important_info', sa.Text(), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('lead_time_hours', sa.Integer(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('cancel_limit_hours', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agendas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agendas_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('picture', sa.String(length=500), nullable=False),
    sa.Column('google_sub', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('company', sa.String(length=160), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('aircraft', sa.String(length=40), nullable=False),
    sa.Column('liters', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_admin', sa.Boolean(), nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_agenda_id'), ['agenda_id'], unique=False)
        batch_op.create_index('ix_bookings_agenda_start_status', ['agenda_id', 'starts_at', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_user_id'), ['user_id'], unique=False)

    op.create_table('closures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('closures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_closures_agenda_id'), ['agenda_id'], unique=False)

    op.create_table('schedule_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agenda_id', 'weekday', 'start_time', name='uq_rule_agenda_day_start')
    )
    with op.batch_alter_table('schedule_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_rules_agenda_id'), ['agenda_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte el cambio."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_rules_agenda_id'))

    op.drop_table('schedule_rules')
    with op.batch_alter_table('closures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_closures_agenda_id'))

    op.drop_table('closures')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_starts_at'))
        batch_op.drop_index('ix_bookings_agenda_start_status')
        batch_op.drop_index(batch_op.f('ix_bookings_agenda_id'))

    op.drop_table('bookings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('agendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendas_slug'))

    op.drop_table('agendas')
    # ### end Alembic commands ###
