"""numero de vuelo en turnos

Revision ID: 7c2f13298ed3
Revises: c33ad79589eb
Fecha: 2026-08-20 16:56:35.727319-03:00

REVISAR ANTES DE APLICAR:

  * Columna NOT NULL nueva sobre una tabla con datos: agregale server_default,
    o falla tanto en SQLite como en Postgres. Ejemplo:
        batch_op.add_column(sa.Column("campo", sa.String(40),
                                      nullable=False, server_default=""))
    Si no querés que el default quede en el esquema, sacalo después con
    batch_op.alter_column("campo", server_default=None).

  * Renombrar una columna: autogenerate lo detecta como "borrar + crear", o sea
    que PIERDE los datos. Cambialo a mano por alter_column(new_column_name=...).

  * Probá siempre `alembic upgrade head` y `alembic downgrade -1` sobre una copia
    con datos antes de tocar producción.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7c2f13298ed3'
down_revision: str | None = 'c33ad79589eb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Aplica el cambio."""
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('flight_number', sa.String(length=20), nullable=False, server_default='')
        )


def downgrade() -> None:
    """Revierte el cambio."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('flight_number')

    # ### end Alembic commands ###
